import { listPackage } from '@electron/asar';
import assert from 'node:assert/strict';
const archive = process.argv[2] ?? 'dist-release/win-unpacked/resources/app.asar';
const files = listPackage(archive).map(x => x.replaceAll('\\','/'));
assert.ok(files.includes('/src/main.mjs')); assert.ok(files.includes('/assets/icon.png'));
assert.ok(files.includes('/release/update-source.json'));
assert.ok(files.includes('/ui/rich-text.js')); assert.ok(files.includes('/ui/tts.js'));
assert.ok(files.includes('/src/tts-providers.mjs'));
assert.ok(files.includes('/ui/hancock.js'));assert.ok(files.includes('/ui/hancock-character.css'));
assert.ok(files.includes('/ui/hancock-panel.js'));assert.ok(files.includes('/ui/open-source.html'));
assert.ok(files.includes('/ui/providers.js'));assert.ok(files.includes('/src/api-endpoint.mjs'));
assert.ok(files.includes('/src/provider-catalog.mjs'));assert.ok(files.includes('/src/provider-status.mjs'));assert.ok(files.includes('/src/response-metadata.mjs'));
assert.ok(files.includes('/THIRD_PARTY_NOTICES.md'));assert.ok(files.includes('/licenses/inventory.json'));
assert.ok(files.includes('/node_modules/@xmldom/xmldom/lib/dom-parser.js'));
assert.ok(files.includes('/node_modules/marked/lib/marked.umd.js'));
assert.ok(files.includes('/node_modules/dompurify/dist/purify.min.js'));
assert.ok(files.includes('/node_modules/katex/dist/katex.min.js'));
assert.ok(files.includes('/node_modules/katex/dist/katex.min.css'));
assert.ok(files.includes('/node_modules/katex/dist/fonts/KaTeX_Main-Regular.woff2'));
assert.ok(!files.some(x => /\.(vault|log|tmp)$/.test(x) || /^\/(data|work|test|\.git|\.env)(\/|$)/.test(x)));
assert.ok(!files.some(x => /\/node_modules\/electron\/|\/node_modules\/electron-builder\//.test(x)));
assert.ok(!files.some(x => /\/node_modules\/(electron-updater|lazy-val)(\/|$)/.test(x)));
const inventory=JSON.parse((await import('@electron/asar')).extractFile(archive,'licenses/inventory.json').toString());
assert.ok(inventory.records.every(r=>!r.missingLicense));
assert.ok(!inventory.records.some(r=>['electron-updater','lazy-val'].includes(r.name)));
console.log(JSON.stringify({ packageChecked: true, encryptedUserDataIncluded: false, developmentRuntimeIncluded: false }));
