import assert from 'node:assert/strict';
import { writeFile, readFile } from 'node:fs/promises';
import { dialog } from 'electron';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { SettingsStore } from './settings-store.mjs';
import { CredentialStore } from './credential-store.mjs';
import { SessionStore } from './session-store.mjs';

export async function verifyUpdate({ root, dataDir, window, store, settings, credentials, workflows, attachments, jobs, cipher, publish, snapshot }) {
  const run = code => window.webContents.executeJavaScript(code);
  const json = data => new Response(JSON.stringify(data));
  const previousFetch = globalThis.fetch;let delayComfy=false;let promptPosts=0;
  const previousSaveDialog = dialog.showSaveDialog;
  const imageBytes = await readFile(join(root, 'assets/icon.png'));
  const exportFile = join(dataDir, 'fixture-export.png');
  dialog.showSaveDialog = async () => ({ canceled: false, filePath: exportFile });
  globalThis.fetch = async (url, init) => {
    assert.equal(init.redirect, 'error');
    if (url.includes('api.github.com')) return url.endsWith('/releases/latest') ? new Response('', { status: 404 }) : json({ private: false, full_name: 'FixtureOwner/FixtureUpdates' });
    if (url.includes('gateway.example')) {
      assert.equal(init.headers.Authorization, 'Bearer FAKE-UI-TEST-KEY');
      return json({ data: [{ id: 'old-alias' }, { id: 'new-alias' }] });
    }
    if (url.endsWith('/system_stats')) return json({ system: { os: 'linux' } });
    if (url.endsWith('/object_info')) return json({ UnetLoaderGGUF: { input: { required: { unet_name: [['Qwen-Image-2.1.gguf']] } } } });
    if (url.endsWith('/queue')) return json({queue_pending:[],queue_running:[[0,'ui-prompt']]});
    if (url.endsWith('/prompt')) {promptPosts++; const body = JSON.parse(init.body); assert.equal(body.prompt['1'].inputs.text, 'UI-COMFY-PROMPT'); assert.equal(body.prompt['3'].inputs.width, 768); assert.equal(body.prompt['4'].inputs.seed, 8); return json({ prompt_id: 'ui-prompt' }); }
    if (url.endsWith('/history/ui-prompt')) {if(delayComfy)return json({});return json({ 'ui-prompt': { status: { completed: true, status_str: 'success' }, outputs: { '5': { images: [{ filename: 'ui-image.png', subfolder: '', type: 'output' }] } } } });
    }
    if (url.includes('/view?')) return new Response(imageBytes);
    throw new Error('Unexpected fixture request');
  };
  const report = { version: snapshot().updates.version };
  try {
    await settings.commit({ version: 1, profiles: [], activeId: null });
    const ref = await credentials.add('https://gateway.example', { type: 'bearer', token: 'FAKE-UI-TEST-KEY' });
    await settings.importServer({ type: 'openai-chat', name: 'Gateway', baseUrl: 'https://gateway.example', authRef: ref, authType: 'bearer', models: [{ name: 'old-alias', type: 'openai-chat' }] });
    const profile = settings.db.profiles[0]; await settings.toggle(profile.id, true); await settings.select(profile.id);
    await store.create(); store.active.messages.push({ id: randomUUID(), role: 'user', content: 'UPDATE-UI-HISTORY', state: 'complete', createdAt: new Date().toISOString() }); await store.save();
    publish(); await run(`document.querySelector('#settings-button').click()`);
    const inside = await run(`(() => { const b = document.querySelector('#settings-dialog').getBoundingClientRect(); return {x: Math.round(b.left + 15), y: Math.round(b.top + 15)}; })()`);
    for (const type of ['mouseDown', 'mouseUp']) window.webContents.sendInputEvent({ type, ...inside, button: 'left', clickCount: 1 });
    await new Promise(resolve => setTimeout(resolve, 100));
    report.insideClickKeepsSettings = await run(`document.querySelector('#settings-dialog').open`); assert.ok(report.insideClickKeepsSettings);
    for (const type of ['mouseDown', 'mouseUp']) window.webContents.sendInputEvent({ type, x: 3, y: 3, button: 'left', clickCount: 1 });
    await new Promise(resolve => setTimeout(resolve, 100));
    report.backdropClosesSettings = await run(`!document.querySelector('#settings-dialog').open`); assert.ok(report.backdropClosesSettings);
    await run(`document.querySelector('#settings-button').click();`);
    const refreshed = await run(`window.qwenChat.refreshServer(${JSON.stringify(profile.id)})`); assert.ok(refreshed.ok);
    report.newModelsListedDisabled = settings.db.profiles.some(p => p.model === 'new-alias' && !p.enabled) && settings.active.id === profile.id; assert.ok(report.newModelsListedDisabled);
    await run(`document.querySelector('.profile-remove[data-profile=${JSON.stringify(profile.id)}]').click(); document.querySelector('#delete-confirm-cancel').click()`);
    assert.equal(settings.db.profiles.length, 2); report.deleteCanBeCancelled = true;
    await run(`document.querySelector('.profile-remove[data-profile=${JSON.stringify(profile.id)}]').click(); document.querySelector('#delete-confirm-yes').click()`);
    await until(() => !snapshot().settingsBusy && settings.db.profiles.length === 1);
    report.removingActiveKeepsHistory = !settings.active && store.active.messages[0].content === 'UPDATE-UI-HISTORY'; assert.ok(report.removingActiveKeepsHistory);
    assert.equal(Object.keys(credentials.db.entries).length, 1);
    await run(`window.qwenChat.refreshServer(${JSON.stringify(settings.db.profiles[0].id)})`); assert.equal(settings.db.profiles.length, 1);
    report.removedModelNotRecreated = true;
    const remaining = settings.db.profiles[0];
    await run(`document.querySelector('.server-remove[data-profile=${JSON.stringify(remaining.id)}]').click(); document.querySelector('#delete-confirm-yes').click()`);
    await until(() => !snapshot().settingsBusy && !settings.db.profiles.length);
    assert.equal(Object.keys(credentials.db.entries).length, 0); report.serverAndUnusedSecretRemoved = true;
    const added = await run(`window.qwenChat.addServer({type: 'comfyui', name: 'ComfyUI', baseUrl: 'https://comfy.example', auth: {type: 'none'}})`); assert.ok(added.ok);
    const comfy = settings.db.profiles[0]; assert.equal(comfy.type, 'comfyui'); assert.equal(comfy.enabled, false);
    report.comfyConnectionPrepared = comfy.serverInfo.ggufAvailable;
    const graph = { '1': { class_type: 'CLIPTextEncode', inputs: { text: 'WORKFLOW-UI-PRIVATE' } }, '2': { class_type: 'CLIPTextEncode', inputs: { text: '' } }, '3': { class_type: 'EmptyLatentImage', inputs: { width: 1024, height: 1024 } }, '4': { class_type: 'KSampler', inputs: { steps: 20, seed: 1, positive: ['1', 0] } }, '5': { class_type: 'SaveImage', inputs: { images: ['4', 0] } } };
    assert.equal((await run(`window.qwenChat.toggleProfile(${JSON.stringify(comfy.id)}, true)`)).ok, false);
    await workflows.import(comfy, 'api-workflow.json', graph); publish();
    report.workflowSummaryVisible = await run(`document.querySelector('#profile-list').textContent.includes('api-workflow.json') && !document.querySelector('#profile-list').textContent.includes('WORKFLOW-UI-PRIVATE')`); assert.ok(report.workflowSummaryVisible);
    const mapping = { prompt: { nodeId: '1', input: 'text' }, negativePrompt: { nodeId: '2', input: 'text' }, width: { nodeId: '3', input: 'width' }, height: { nodeId: '3', input: 'height' }, steps: { nodeId: '4', input: 'steps' }, seed: { nodeId: '4', input: 'seed' }, outputNode: '5' };
    await run(`document.querySelector('.workflow-configure').click();`);
    for (const [field, target] of Object.entries(mapping)) await run(`document.querySelector(${JSON.stringify(field === 'outputNode' ? '#workflow-output' : '#mapping-' + field)}).value = ${JSON.stringify(field === 'outputNode' ? target : JSON.stringify(target))}`);
    await run(`document.querySelector('#workflow-form').requestSubmit()`);
    await until(() => !snapshot().settingsBusy && workflows.summary(comfy).ready);
    report.workflowMappingSaved = true;
    assert.equal((await run(`window.qwenChat.toggleProfile(${JSON.stringify(comfy.id)}, true)`)).ok, true);
    assert.equal((await run(`window.qwenChat.selectProfile(${JSON.stringify(comfy.id)})`)).ok, true);
    await run(`document.querySelector('#settings-dialog').close(); document.querySelector('#image-width').value = '768'; document.querySelector('#image-seed').value = '8'; document.querySelector('#message-input').value = 'UI-COMFY-PROMPT'; document.querySelector('#chat-form').requestSubmit();`);
    await until(() => !snapshot().busy && store.active.messages.some(m => m.role === 'assistant' && m.attachmentIds?.length));
    report.comfyImageRendered = await run(`Boolean(document.querySelector('#messages .chat-attachment img')?.src.startsWith('data:image/png;base64,'))`); assert.ok(report.comfyImageRendered);
    await run(`document.querySelector('.image-download').click()`);
    await until(async () => { try { return (await readFile(exportFile)).equals(imageBytes); } catch { return false; } });
    assert.deepEqual(await readFile(exportFile), imageBytes); report.imageExportMatches = true;
    window.showInactive(); await run(`document.querySelector('#image-options').open = true; new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))`);
    await new Promise(resolve => setTimeout(resolve, 200)); await writeFile(join(root, 'preview-comfy-chat.png'), (await window.webContents.capturePage()).toPNG()); window.hide();
    await run(`document.querySelector('#settings-button').click(); document.querySelector('#tab-updates').click(); document.querySelector('#update-repository').value = 'https://github.com/FixtureOwner/FixtureUpdates'; document.querySelector('#update-repository').dispatchEvent(new Event('input')); document.querySelector('#update-source-form').requestSubmit();`);
    await until(() => !snapshot().settingsBusy && settings.db.updateRepository === 'https://github.com/FixtureOwner/FixtureUpdates');
    report.updateSourceSavedAndNoReleaseExplained = await run(`document.querySelector('#update-source-status').textContent.includes('Noch kein stabiles Release')`); assert.ok(report.updateSourceSavedAndNoReleaseExplained);
    const rejected = await run(`window.qwenChat.saveUpdateRepository('https://foreign.example/repo')`); assert.equal(rejected.ok, false); assert.equal(settings.db.updateRepository, 'https://github.com/FixtureOwner/FixtureUpdates'); report.invalidSourceKeepsPrevious = true;
    window.showInactive(); await run(`new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))`);
    await new Promise(resolve => setTimeout(resolve, 200));
    await writeFile(join(root, 'preview-update-settings.png'), (await window.webContents.capturePage()).toPNG());
    window.hide();
    const restoredSettings = new SettingsStore(dataDir, cipher); const restoredCredentials = new CredentialStore(dataDir, cipher); const restoredHistory = new SessionStore(dataDir, cipher);
    await restoredSettings.load(); await restoredCredentials.load(); await restoredHistory.load();
    report.encryptedRestartPreservesChangesAndChats = restoredSettings.db.profiles[0].type === 'comfyui' && !Object.keys(restoredCredentials.db.entries).length && restoredHistory.active.messages[0].content === 'UPDATE-UI-HISTORY' && restoredSettings.db.updateRepository === 'https://github.com/FixtureOwner/FixtureUpdates'; assert.ok(report.encryptedRestartPreservesChangesAndChats);
    const generated = restoredHistory.active.messages.find(m => m.attachmentIds?.length); assert.ok(generated); assert.ok(attachments.get(generated.attachmentIds[0]));
    // A running request locks settings; local stop retains server ID for later GET-only retrieval.
    delayComfy=true;const sendPending=run('window.qwenChat.send("UI-COMFY-PROMPT",[],{width:768,seed:8})');
    await until(()=>snapshot().busy&&jobs.snapshot().some(j=>j.waiting&&j.serverId==='ui-prompt'));
    const waitingJob=jobs.snapshot().find(j=>j.waiting&&j.serverId==='ui-prompt');
    assert.equal((await run('window.qwenChat.toggleProfile('+JSON.stringify(comfy.id)+',false)')).ok,false);
    assert.equal(await run('document.querySelector(".profile-edit").disabled'),true);report.settingsLockedDuringRequest=true;
    await run('window.qwenChat.cancel()');await sendPending;assert.equal(jobs.get(waitingJob.id).serverId,'ui-prompt');assert.equal(jobs.get(waitingJob.id).state,'unknown');
    delayComfy=false;const postsBeforeRecovery=promptPosts;
    assert.equal((await run('window.qwenChat.checkJob('+JSON.stringify(waitingJob.id)+')')).ok,true);
    assert.equal(promptPosts,postsBeforeRecovery);report.localStopRetainsRecoverableJob=true;
    const clone = await run('window.qwenChat.duplicateWorkflowProfile(' + JSON.stringify(comfy.id) + ')'); assert.ok(clone.ok);
    const alternative = settings.db.profiles.find(p => p.id === clone.id);
    const optionalGraph = { '71': { class_type: 'Text', inputs: { text: 'EXAMPLE-ONLY' } }, '72': { class_type: 'Sampler', inputs: { cfg: 6 } }, '73': { class_type: 'SaveImage', inputs: { images: ['72', 0] } } };
    await workflows.import(alternative, 'alternative.json', optionalGraph);
    await workflows.configure(alternative, { prompt: { nodeId: '71', input: 'text' }, cfg: { nodeId: '72', input: 'cfg' }, outputNode: '73' }, { cfg: 6 }); publish();
    await run('window.qwenChat.toggleProfile(' + JSON.stringify(alternative.id) + ', true)');
    await run('window.qwenChat.selectProfile(' + JSON.stringify(alternative.id) + ')');
    await until(async () => await run("Boolean(document.querySelector('#image-cfg'))"));
    assert.equal(await run("Boolean(document.querySelector('#image-width'))"), false); report.onlyConfiguredImageFieldsShown = true;
    assert.equal(workflows.get(comfy).mapping.seed.nodeId, '4'); report.independentWorkflowProfiles = true;
    await run('window.qwenChat.saveProfile(' + JSON.stringify({id:alternative.id,uploads:{files:false,photos:false}}) + ')');
    assert.equal(await run("document.querySelector('#attach-file').disabled"), true); report.uploadSettingsSaved = true;
    assert.equal((await run('window.qwenChat.setBetaUpdates(true)')).ok, true); assert.equal(settings.db.betaUpdates, true); report.betaPersists = true;
    // Persist an accepted job, then simulate restart before completion. Recovery must attach once.
    const recoveredMessage={id:randomUUID(),role:'user',content:'RECOVER-ME',state:'pending',createdAt:new Date().toISOString()};
    store.active.messages.push(recoveredMessage);await store.save();
    const recoveryJob=await jobs.create(comfy,store.active.id,recoveredMessage.id);
    await jobs.update(recoveryJob.id,{serverId:'ui-prompt',outputNode:'5',recoverable:true,state:'running'});await jobs.load();publish();
    assert.equal(jobs.get(recoveryJob.id).state,'unknown');
    assert.equal((await run('window.qwenChat.checkJob('+JSON.stringify(recoveryJob.id)+')')).ok,true);
    assert.equal((await run('window.qwenChat.checkJob('+JSON.stringify(recoveryJob.id)+')')).ok,true);
    assert.equal(store.active.messages.filter(m=>m.jobId===recoveryJob.id&&m.role==='assistant').length,1);report.recoveryAfterRestartNoDuplicate=true;
    const oldUrl=comfy.baseUrl;await settings.upsert({id:comfy.id,baseUrl:'https://other.example',enabled:false});
    assert.equal((await run('window.qwenChat.checkJob('+JSON.stringify(recoveryJob.id)+')')).ok,false);report.changedConnectionBlocksRecovery=true;
    await settings.upsert({id:comfy.id,baseUrl:oldUrl,enabled:false});
    const deletedId = store.active.id; await run("document.querySelector('#settings-dialog').close(); document.querySelector('#delete-chat').click(); document.querySelector('#chat-delete-confirm').click()");
    await until(() => !store.db.sessions.some(s => s.id === deletedId)); report.chatDeletionViaUI = true;
    assert.equal(await run('document.title'), 'KAIROS');
    await writeFile(join(root, 'verification-update.json'), JSON.stringify(report, null, 2)); return report;
  } finally { globalThis.fetch = previousFetch; dialog.showSaveDialog = previousSaveDialog; }
}
async function until(predicate) { for (let n = 0; n < 150; n++) { if (await predicate()) { await new Promise(resolve => setTimeout(resolve, 80)); return; } await new Promise(resolve => setTimeout(resolve, 80)); } throw new Error('Update UI verification timed out'); }
